language: java


jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="7b08a5b3-4c63-45b5-a6da-e800c079af8b"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -vladlen@ufanet.ru
    on_success: never # default: change
    on_failure: always # default: always