language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="d5328a1c-f12d-4eca-acf3-3941e3ab2241"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -vladlen@ufanet.ru
    on_success: never # default: change
    on_failure: always # default: always